AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFront distribution for covid-centre.pharmeasy.in (Akamai v2 parity).
  Implements ALB origin, path-based cache behaviors, no-store caching everywhere,
  GraphQL forwarding, error caching, and optional security headers.

Parameters:
  OriginDomainName:
    Type: String
    Default: "shellkode-cloudformation.s3.us-east-1.amazonaws.com"
    Description: "ALB origin domain for covid-centre.pharmeasy.in"


  ACMCertificateArn:
    Type: String
    Default: "arn:aws:acm:us-east-1:732041584766:certificate/1a034495-681b-4ea6-802b-b96d5cd7070e"
    Description: "ACM certificate ARN in us-east-1 for TLS"

  DomainAliases:
    Type: CommaDelimitedList
    Default: "covid-centre.haristeeltech.com"
    Description: "Domain aliases (CNAMEs) for the distribution"

  ExistingNoStoreCachePolicyId: 
    Type: String
    Default: "8b83fea7-7dee-4315-87f7-e2635c0ce329"
    Description: "Optional OriginRequestPolicy ID for GraphQL (forward all)."

  ExistingORPId:
    Type: String
    Default: "8c7b8a83-bb01-43e7-8e9e-1956702c42c1"
    Description: "Optional OriginRequestPolicy ID for GraphQL (forward all)."

  EnableResponseHeadersPolicy:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]

Resources:

  S3OAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: assets-oac-test
        Description: "OAC for assets.pharmeasy.in S3 origin"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CovidCentreDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: "covid-centre.pharmeasy.in CloudFront (Akamai parity)"
        Aliases: !Ref DomainAliases
        HttpVersion: http2and3
        IPV6Enabled: true
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        Origins:
          - Id: alb-origin
            DomainName: !Ref OriginDomainName
            OriginAccessControlId: !Ref S3OAC
            S3OriginConfig:
              OriginReadTimeout: 60

        DefaultCacheBehavior:
          TargetOriginId: alb-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
          CachedMethods: [GET, HEAD]
          CachePolicyId: !Ref ExistingNoStoreCachePolicyId
          OriginRequestPolicyId: !Ref ExistingORPId
#          ResponseHeadersPolicyId: !If [ AttachResponseHeaders, !Ref ExistingResponseHeadersPolicyId, !Ref "AWS::NoValue" ]
          Compress: true

        CacheBehaviors:
          # GraphQL
          - PathPattern: "/graphql*"
            TargetOriginId: alb-origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachedMethods: [GET, HEAD]
            CachePolicyId: !Ref ExistingNoStoreCachePolicyId
        /#    OriginRequestPolicyId: !Ref ExistingORPId
#            ResponseHeadersPolicyId: !If [ AttachResponseHeaders, !Ref ExistingResponseHeadersPolicyId, !Ref "AWS::NoValue" ]
            Compress: true

Outputs:
  DistributionId:
    Value: !Ref CovidCentreDistribution
    Description: "CloudFront distribution ID"

  DistributionDomainName:
    Value: !GetAtt CovidCentreDistribution.DomainName
    Description: "CloudFront distribution domain name"
